// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addResponse.proto

package railway_ipc_sample

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddResponse struct {
	UserUuid             string            `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CorrelationId        string            `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Uuid                 string            `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Context              map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 *AddResponse_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c0978d1aa9e67ad, []int{0}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *AddResponse) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *AddResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddResponse) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *AddResponse) GetData() *AddResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddResponse_Data struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse_Data) Reset()         { *m = AddResponse_Data{} }
func (m *AddResponse_Data) String() string { return proto.CompactTextString(m) }
func (*AddResponse_Data) ProtoMessage()    {}
func (*AddResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c0978d1aa9e67ad, []int{0, 0}
}

func (m *AddResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse_Data.Unmarshal(m, b)
}
func (m *AddResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse_Data.Marshal(b, m, deterministic)
}
func (m *AddResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse_Data.Merge(m, src)
}
func (m *AddResponse_Data) XXX_Size() int {
	return xxx_messageInfo_AddResponse_Data.Size(m)
}
func (m *AddResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse_Data proto.InternalMessageInfo

func (m *AddResponse_Data) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*AddResponse)(nil), "railway_ipc.sample.AddResponse")
	proto.RegisterMapType((map[string]string)(nil), "railway_ipc.sample.AddResponse.ContextEntry")
	proto.RegisterType((*AddResponse_Data)(nil), "railway_ipc.sample.AddResponse.Data")
}

func init() {
	proto.RegisterFile("addResponse.proto", fileDescriptor_4c0978d1aa9e67ad)
}

var fileDescriptor_4c0978d1aa9e67ad = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0x4b, 0x4b, 0xf4, 0x40,
	0x10, 0x24, 0xaf, 0xfd, 0xbe, 0xed, 0xa8, 0x68, 0x23, 0x12, 0x56, 0x90, 0x20, 0x0a, 0x39, 0x48,
	0x0e, 0xeb, 0x65, 0xd9, 0x9b, 0xf8, 0x00, 0xaf, 0x03, 0x9e, 0x43, 0x9b, 0x99, 0xc3, 0xe0, 0x98,
	0x09, 0xf3, 0x50, 0xf3, 0xfb, 0xfc, 0x63, 0x92, 0xd9, 0x88, 0x01, 0x0f, 0xde, 0xba, 0x7a, 0xaa,
	0xa6, 0xab, 0x0a, 0x8e, 0x88, 0x73, 0x26, 0x6c, 0xaf, 0x3b, 0x2b, 0xea, 0xde, 0x68, 0xa7, 0x11,
	0x0d, 0x49, 0xf5, 0x4e, 0x43, 0x23, 0xfb, 0xb6, 0xb6, 0xf4, 0xda, 0x2b, 0x71, 0xfe, 0x19, 0x43,
	0x7e, 0xf3, 0xc3, 0xc4, 0x53, 0x58, 0x7a, 0x2b, 0x4c, 0xe3, 0xbd, 0xe4, 0x45, 0x54, 0x46, 0xd5,
	0x92, 0xfd, 0x1f, 0x17, 0x4f, 0x5e, 0x72, 0xbc, 0x84, 0x83, 0x56, 0x1b, 0x23, 0x14, 0x39, 0xa9,
	0xbb, 0x46, 0xf2, 0x22, 0x0e, 0x8c, 0xfd, 0xd9, 0xf6, 0x91, 0x23, 0x42, 0x1a, 0xe4, 0x49, 0x78,
	0x0c, 0x33, 0x3e, 0xc0, 0xbf, 0x56, 0x77, 0x4e, 0x7c, 0xb8, 0x22, 0x2d, 0x93, 0x2a, 0x5f, 0x5f,
	0xd5, 0xbf, 0xdd, 0xd4, 0x33, 0x27, 0xf5, 0xed, 0x8e, 0x7e, 0xdf, 0x39, 0x33, 0xb0, 0x6f, 0x31,
	0x6e, 0x20, 0xe5, 0xe4, 0xa8, 0xc8, 0xca, 0xa8, 0xca, 0xd7, 0x17, 0x7f, 0x7d, 0x72, 0x47, 0x8e,
	0x58, 0x50, 0xac, 0xce, 0x20, 0x1d, 0x11, 0x9e, 0xc0, 0xc2, 0x08, 0xeb, 0x95, 0x0b, 0xf1, 0x32,
	0x36, 0xa1, 0xd5, 0x16, 0xf6, 0xe6, 0x27, 0xf1, 0x10, 0x92, 0x17, 0x31, 0x4c, 0x1d, 0x8c, 0x23,
	0x1e, 0x43, 0xf6, 0x46, 0xca, 0x8b, 0x29, 0xf5, 0x0e, 0x6c, 0xe3, 0x4d, 0xf4, 0xbc, 0x08, 0x05,
	0x5f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x31, 0x1f, 0x0b, 0x8d, 0x75, 0x01, 0x00, 0x00,
}
