// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addRequest.proto

package railway_ipc_sample

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	UserUuid             string            `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CorrelationId        string            `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Uuid                 string            `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Context              map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 *AddRequest_Data  `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3cf3b5f54796cc5, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *AddRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *AddRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AddRequest) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *AddRequest) GetData() *AddRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddRequest_Data struct {
	Op1                  int32    `protobuf:"varint,1,opt,name=op1,proto3" json:"op1,omitempty"`
	Op2                  int32    `protobuf:"varint,2,opt,name=op2,proto3" json:"op2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest_Data) Reset()         { *m = AddRequest_Data{} }
func (m *AddRequest_Data) String() string { return proto.CompactTextString(m) }
func (*AddRequest_Data) ProtoMessage()    {}
func (*AddRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3cf3b5f54796cc5, []int{0, 0}
}

func (m *AddRequest_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest_Data.Unmarshal(m, b)
}
func (m *AddRequest_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest_Data.Marshal(b, m, deterministic)
}
func (m *AddRequest_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest_Data.Merge(m, src)
}
func (m *AddRequest_Data) XXX_Size() int {
	return xxx_messageInfo_AddRequest_Data.Size(m)
}
func (m *AddRequest_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest_Data.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest_Data proto.InternalMessageInfo

func (m *AddRequest_Data) GetOp1() int32 {
	if m != nil {
		return m.Op1
	}
	return 0
}

func (m *AddRequest_Data) GetOp2() int32 {
	if m != nil {
		return m.Op2
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "railway_ipc.sample.AddRequest")
	proto.RegisterMapType((map[string]string)(nil), "railway_ipc.sample.AddRequest.ContextEntry")
	proto.RegisterType((*AddRequest_Data)(nil), "railway_ipc.sample.AddRequest.Data")
}

func init() {
	proto.RegisterFile("addRequest.proto", fileDescriptor_a3cf3b5f54796cc5)
}

var fileDescriptor_a3cf3b5f54796cc5 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0xa5, 0x5f, 0xea, 0xce, 0xaa, 0x2c, 0x83, 0x87, 0xb2, 0x5e, 0x8a, 0x22, 0x14, 0x85, 0x80,
	0xf5, 0xa0, 0xec, 0x4d, 0x74, 0x0f, 0x5e, 0x03, 0x9e, 0xcb, 0xd8, 0xe4, 0x10, 0xac, 0x4d, 0x4d,
	0x13, 0xb5, 0xff, 0xd1, 0x1f, 0x25, 0x49, 0x57, 0x5d, 0xf0, 0xe0, 0xed, 0xcd, 0xcb, 0x7b, 0x99,
	0x79, 0x0f, 0x16, 0x24, 0x04, 0x97, 0xaf, 0x4e, 0x0e, 0x96, 0xf5, 0x46, 0x5b, 0x8d, 0x68, 0x48,
	0xb5, 0xef, 0x34, 0xd6, 0xaa, 0x6f, 0xd8, 0x40, 0x2f, 0x7d, 0x2b, 0x4f, 0x3e, 0x63, 0x80, 0xdb,
	0x1f, 0x21, 0x1e, 0xc3, 0xcc, 0x0d, 0xd2, 0xd4, 0xce, 0x29, 0x91, 0x47, 0x45, 0x54, 0xce, 0xf8,
	0x9e, 0x27, 0x1e, 0x9d, 0x12, 0x78, 0x06, 0x87, 0x8d, 0x36, 0x46, 0xb6, 0x64, 0x95, 0xee, 0x6a,
	0x25, 0xf2, 0x38, 0x28, 0x0e, 0xb6, 0xd8, 0x07, 0x81, 0x08, 0x69, 0xb0, 0x27, 0xe1, 0x31, 0x60,
	0x5c, 0xc3, 0x6e, 0xa3, 0x3b, 0x2b, 0x3f, 0x6c, 0x9e, 0x16, 0x49, 0x39, 0xaf, 0x2e, 0xd8, 0xdf,
	0x63, 0xd8, 0xef, 0x21, 0xec, 0x6e, 0x52, 0xaf, 0x3b, 0x6b, 0x46, 0xfe, 0xed, 0xc5, 0x6b, 0x48,
	0x05, 0x59, 0xca, 0xb3, 0x22, 0x2a, 0xe7, 0xd5, 0xe9, 0x3f, 0x7f, 0xdc, 0x93, 0x25, 0x1e, 0x0c,
	0xcb, 0x73, 0x48, 0xfd, 0x84, 0x0b, 0x48, 0x74, 0x7f, 0x19, 0x92, 0x65, 0xdc, 0xc3, 0x89, 0xa9,
	0x42, 0x92, 0xc0, 0x54, 0xcb, 0x15, 0xec, 0x6f, 0x6f, 0xf7, 0x8a, 0x67, 0x39, 0x6e, 0xda, 0xf0,
	0x10, 0x8f, 0x20, 0x7b, 0xa3, 0xd6, 0xc9, 0x4d, 0xfe, 0x69, 0x58, 0xc5, 0x37, 0xd1, 0xd3, 0x4e,
	0x68, 0xfa, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x52, 0x92, 0xb4, 0xdf, 0x7d, 0x01, 0x00, 0x00,
}
